spring.application.name=ServiceflowOsApplication
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/serviceflow
spring.datasource.username=serviceflow
spring.datasource.password=serviceflow_dev

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
